<?php
session_start();
require_once __DIR__ . '/audit_helper.php';
require_once __DIR__ . '/dompdf/autoload.inc.php';   // same loader you already use

use Dompdf\Dompdf;
use Dompdf\Options;

//--------- DB ---------
$host = "localhost";
$user = "u803144294_system";  
$pass = "3AINS-G7_db"; 
$db   = "u803144294_system";
$conn = new mysqli($host, $user, $pass, $db);
if ($conn->connect_error) die("DB Connection failed: " . $conn->connect_error);

//--------- FILTER (keep params but don't include leading WHERE) ---------
$date = $_GET['date'] ?? '';
$cond = '';        // will hold additional AND conditions (no leading WHERE)
$params = [];
$types  = '';
if ($date) {
    $start = $date . ' 00:00:00';
    $end   = $date . ' 23:59:59';
    $cond  = " AND b.created_at BETWEEN ? AND ?";
    $params = [$start, $end];
    $types  = 'ss';
}

//--------- BALLOTS + CHOICES (only ballots that have at least one vote) ---------
$sql = "SELECT DISTINCT b.ballot_id
        FROM ballots b
        WHERE EXISTS (
            SELECT 1 FROM votes v WHERE v.ballot_id = b.ballot_id
        )
        $cond
        ORDER BY b.ballot_id ASC";

$stmt = $conn->prepare($sql);
if ($params) {
    $stmt->bind_param($types, ...$params);
}
$stmt->execute();
$ballots = $stmt->get_result()->fetch_all(MYSQLI_ASSOC);
$stmt->close();

foreach ($ballots as &$b) {
    $bid = $b['ballot_id'];
    $q = $conn->prepare("SELECT p.position_name, u.full_name AS candidate_name, u.user_id AS candidate_user_id
                         FROM votes v
                         JOIN candidates ca ON v.candidate_id = ca.candidate_id
                         JOIN positions p ON ca.position_id = p.position_id
                         JOIN users u ON ca.user_id = u.user_id
                         WHERE v.ballot_id = ?
                         ORDER BY p.position_id ASC");
    $q->bind_param('i', $bid);
    $q->execute();
    $b['choices'] = $q->get_result()->fetch_all(MYSQLI_ASSOC);
    $q->close();
}

//--------- PDF STYLING (same as export_results.php) ---------
$umak_logo_file = __DIR__ . '/UMAK.png';
$sc_logo_file = __DIR__ . '/sc.png';
$umak_logo_b64 = file_exists($umak_logo_file)
    ? 'data:image/' . pathinfo($umak_logo_file, PATHINFO_EXTENSION) . ';base64,' . base64_encode(file_get_contents($umak_logo_file))
    : '';
$sc_logo_b64 = file_exists($sc_logo_file)
    ? 'data:image/' . pathinfo($sc_logo_file, PATHINFO_EXTENSION) . ';base64,' . base64_encode(file_get_contents($sc_logo_file))
    : '';

$html = '<!doctype html>
<html><head>
<meta charset="utf-8">
<title>Ballots List</title>
<style>
body { font-family: DejaVu Sans, Arial, sans-serif; font-size:12px; color:#222; }
.header-table { width:100%; margin-bottom:8px; }
.header-table td { vertical-align:middle; }
.logo { width:70px; height:auto; }
.title-main { text-align:center; }
.title-main h2 { margin:0; color:#000; font-size:18px; font-weight:800; }
.title-main p { margin:2px 0 6px; font-size:12px; color:#333; }
.ballot { page-break-after:always; border:1px solid #ddd; padding:16px; margin:8px 0; }
.ballot h3 { margin:0 0 8px; }
.pos { margin:6px 0; padding:6px; background:#f6f8fb; border-radius:4px; }
.footer { text-align:center; font-size:10px; color:#666; margin-top:14px; }
</style>
</head><body>';

//--------- HEADER ---------
$html .= '<table class="header-table"><tr>';
$html .= '<td style="width:18%; text-align:left;">' . ($umak_logo_b64 ? "<img src=\"$umak_logo_b64\" class=\"logo\">" : '') . '</td>';
$html .= '<td style="width:64%; text-align:center;" class="title-main">
            <h2>UNIVERSITY OF MAKATI</h2>
            <p>University Student Council — Student Election Ballots</p>
          </td>';
$html .= '<td style="width:18%; text-align:right;">' . ($sc_logo_b64 ? "<img src=\"$sc_logo_b64\" class=\"logo\">" : '') . '</td>';
$html .= '</tr></table>';

//--------- BODY ---------
if (!$ballots) {
    $html .= '<div class="ballot"><h3>No ballots found for the selected filter.</h3></div>';
} else {
    foreach ($ballots as $b) {
        $html .= '<div class="ballot"><h3>Ballot #'.htmlspecialchars($b['ballot_id']).'</h3>';
        if (!$b['choices']) {
            $html .= '<div class="pos">No votes recorded (voter skipped all positions).</div>';
        } else {
            foreach ($b['choices'] as $c) {
                $html .= '<div class="pos"><strong>'.htmlspecialchars($c['position_name']).':</strong> '
                      .htmlspecialchars($c['candidate_name']).' (ID: '.htmlspecialchars($c['candidate_user_id']).')</div>';
            }
        }
        $html .= '</div>';
    }
}

$html .= '<div class="footer">Generated by UMAK E-Vote System — '.date('F d, Y h:i A').'</div>';
$html .= '</body></html>';

//--------- DOMPDF ---------
$options = new Options();
$options->set('isRemoteEnabled', true);
$options->set('defaultFont', 'DejaVu Sans');
$dompdf = new Dompdf($options);
$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'portrait');
$dompdf->render();

//--------- SAVE PDF TO AUDIT_EXPORTS FOLDER ---------
$export_dir = __DIR__ . '/audit_exports';
if (!is_dir($export_dir)) {
    mkdir($export_dir, 0755, true);
}

$timestamp = date('Y-m-d_H-i-s');
$admin_id = $_SESSION['user_id'] ?? 'unknown';
$filename = "ballots_{$admin_id}_{$timestamp}.pdf";
$filepath = $export_dir . '/' . $filename;

$pdf_content = $dompdf->output();
file_put_contents($filepath, $pdf_content);

//--------- AUDIT LOG WITH FILE REFERENCE ---------
$admin_uid = $_SESSION['user_id'] ?? 0;
log_action($conn, $admin_uid, "Exported ballot list PDF - File: {$filename}" . ($date ? " (date: {$date})" : ""));

//--------- STREAM TO BROWSER ---------
header('Content-Type: application/pdf');
header('Content-Disposition: inline; filename="UMAK_Ballots_' . ($date ?: 'all') . '.pdf"');
echo $pdf_content;

exit;
?>